

# This file was *autogenerated* from the file day24.sage
from sage.all_cmdline import *   # import sage library

_sage_const_19p0 = RealNumber('19.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_13p0 = RealNumber('13.0'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_30p0 = RealNumber('30.0'); _sage_const_18p0 = RealNumber('18.0'); _sage_const_22p0 = RealNumber('22.0'); _sage_const_20p0 = RealNumber('20.0'); _sage_const_25p0 = RealNumber('25.0'); _sage_const_34p0 = RealNumber('34.0'); _sage_const_4p0 = RealNumber('4.0'); _sage_const_12p0 = RealNumber('12.0'); _sage_const_31p0 = RealNumber('31.0'); _sage_const_28p0 = RealNumber('28.0'); _sage_const_5p0 = RealNumber('5.0'); _sage_const_15p0 = RealNumber('15.0'); _sage_const_3p0 = RealNumber('3.0')
var('x1', 'y1', 'z1', 'vx1', 'vy1', 'vz1')
var('t0')
eqX0 = x1 + vx1 * t0 == _sage_const_19p0  + -_sage_const_2p0  * t0
eqY0 = y1 + vy1 * t0 == _sage_const_13p0  + _sage_const_1p0  * t0
eqZ0 = z1 + vz1 * t0 == _sage_const_30p0  + -_sage_const_2p0  * t0
var('t1')
eqX1 = x1 + vx1 * t1 == _sage_const_18p0  + -_sage_const_1p0  * t1
eqY1 = y1 + vy1 * t1 == _sage_const_19p0  + -_sage_const_1p0  * t1
eqZ1 = z1 + vz1 * t1 == _sage_const_22p0  + -_sage_const_2p0  * t1
var('t2')
eqX2 = x1 + vx1 * t2 == _sage_const_20p0  + -_sage_const_2p0  * t2
eqY2 = y1 + vy1 * t2 == _sage_const_25p0  + -_sage_const_2p0  * t2
eqZ2 = z1 + vz1 * t2 == _sage_const_34p0  + -_sage_const_4p0  * t2
var('t3')
eqX3 = x1 + vx1 * t3 == _sage_const_12p0  + -_sage_const_1p0  * t3
eqY3 = y1 + vy1 * t3 == _sage_const_31p0  + -_sage_const_2p0  * t3
eqZ3 = z1 + vz1 * t3 == _sage_const_28p0  + -_sage_const_1p0  * t3
var('t4')
eqX4 = x1 + vx1 * t4 == _sage_const_20p0  + _sage_const_1p0  * t4
eqY4 = y1 + vy1 * t4 == _sage_const_19p0  + -_sage_const_5p0  * t4
eqZ4 = z1 + vz1 * t4 == _sage_const_15p0  + -_sage_const_3p0  * t4
S = solve([eqX0, eqY0, eqZ0, eqX1, eqY1, eqZ1, eqX2, eqY2, eqZ2, eqX3, eqY3, eqZ3, eqX4, eqY4, eqZ4], [x1, y1, z1, vx1, vy1, vz1, t0, t1, t2, t3, t4])
x1 + y1 + z1

